// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectAMQP(arg1, arg2) {
  return window['go']['main']['App']['ConnectAMQP'](arg1, arg2);
}

export function ConnectMQTT(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ConnectMQTT'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DisconnectAMQP() {
  return window['go']['main']['App']['DisconnectAMQP']();
}

export function DisconnectMQTT() {
  return window['go']['main']['App']['DisconnectMQTT']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function PublishAMQP(arg1, arg2, arg3) {
  return window['go']['main']['App']['PublishAMQP'](arg1, arg2, arg3);
}

export function PublishMQTT(arg1, arg2) {
  return window['go']['main']['App']['PublishMQTT'](arg1, arg2);
}

export function SaveProfile(arg1, arg2) {
  return window['go']['main']['App']['SaveProfile'](arg1, arg2);
}

export function StartConsumeAMQP() {
  return window['go']['main']['App']['StartConsumeAMQP']();
}

export function StopConsumeAMQP() {
  return window['go']['main']['App']['StopConsumeAMQP']();
}
