// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectAMQP(arg1:string,arg2:string):Promise<void>;

export function ConnectMQTT(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DisconnectAMQP():Promise<void>;

export function DisconnectMQTT():Promise<void>;

export function GetProfiles():Promise<Record<string, main.Profile>>;

export function PublishAMQP(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PublishMQTT(arg1:string,arg2:string):Promise<void>;

export function SaveProfile(arg1:string,arg2:main.Profile):Promise<void>;

export function StartConsumeAMQP():Promise<void>;

export function StopConsumeAMQP():Promise<void>;
